### ISSUE TITLE
warning: missing field initializer

### ISSUE THREAD

**Issue by JeffAbrahamson** [google/cctz#10]
When compiling thus

    clang++ -ggdb3 -Wall -Wextra -std=c++14  -c -fpic -o cctz_fmt.o cctz_fmt.cc

I see warnings at lines 31, 482, and 637 about a missing field tm_min.

    warning: missing field 'tm_min' initializer [-Wmissing-field-initializers]

Similarly, clang++ complains of `type_index` missing at 808 of cctz_info.cc.

Perhaps an old-fashioned `memset(&tm, 0, sizeof(tm))` would be better?

**Comment by devjgm** [comment]
JFYI, I'm not ignoring this, I've just been sick. I'll be back soon. Thanks.

**Comment by devbww** [comment]
Hi Jeff,

I've fixed the cctz_info.cc:808 instance as that is an internal structure that we know the exact shape of.

However, struct tm is a different beast.  We really do want zero initialization of all the fields, and in whatever order they are defined (which can be different from a memset() for non-integral fields).  So, our conclusion is that -Wmissing-field-initializers just gives too many false positives to be useful.

I have changed the tm initializations to the C++11 style of "std::tm tm{}" however.  Perhaps the warning will eventually disappear for such incantations.

Thanks.

**Comment by JeffAbrahamson** [comment]
Thanks for the fix and the comment.

Why does initialization _order_ matter within the structure?  Not meaning to be pedantic : I think you're referring to commits 51e9cfb382d9378ca77515ab3f5cbe22a359e362 and fc677c4b88976bb4363d0f14c7360ae932642e44, neither of which adds more explanation in code or in commit message, so I'm following on in the issue.

**Comment by devbww** [comment]
By "order" I meant the order of the fields within std::tm.  Different systems have different tm fields, so it is impossible to set them all explicitly in portable code.  The best we can do is zero initialize the whole structure and then reset the fields we want by their (standard) names.

Aside:  We do use a couple of non-standard field names, tm_gmtoff and tm_zone, in the cctz_libc implementation used for "libc:<zone>" names.

Commit [51e9cfb](https://github.com/google/cctz/commit/51e9cfb382d9378ca77515ab3f5cbe22a359e362) should be uncontroversial.

**Comment by JeffAbrahamson** [comment]
Just to be clear, the result of the commits is that the compiler warnings are now gone, and I wasn't questioning code correctness, just the distraction of having to decide myself if the compiler was hallucinating or prescient.

The point on which I'm unclear is only why `memset(&tm, 0, sizeof(tm))` didn't do what you want.  It sounded like maybe you were saying that in the presence of a non-integer field (currently none, but hey, maybe some day) `memset` to zero is not guaranteed to be the same as `float x = 0.0;`?

**Comment by devbww** [comment]
I was still seeing the -Wmissing-field-initializers warnings on the new "std::tm tm{};" declarations (from gcc).

Yes ... the presence of non-integer fields.  But it is not a someday thing---most systems already have some form of "const char* tm_zone" field.

**Comment by devjgm** [comment]
JFYI:
Also note that clang++ with `-Wmissing-field-initializers` does *not* warn about `std::tm tm{};`. So it appears that this is a bug (for some definition of "bug") in gcc. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55805. 

Note that gcc-5 has already been "fixed" to not warn when given an initialization like `std::tm tm{};`.
