### ISSUE TITLE
MSVC2019 C4496 error: strcpy function may be unsafe

### ISSUE THREAD

**Issue by mireiner** [google/cctz#106]
Hi there,

on Windows the MSVC2019 compiler gives error messages:

error C4996:  'strcpy': This function may be unsafe. Consider using strcpy_s instead.

Line 104 in time_zone_fixed.cc
Line 311 in time_tool.cc

I wondered why you use different versions of strcpy:
std::strcpy(..) in time_zone_fixed.cc and strcpy(..) in time_tool.cc.

To solve the error message just use the c++11 functions (without leading std::) instead:
strcpy_s(dest, sizeof(dest), src) or strcpy_s(dest, src).

The shorter strcpy_s(dest, src) is an overloaded template function. Don't now how compatible it is. But the longer strcpy_s(dest, sizeof(dest), src) should be fine.

Best regards,
mireiner

**Comment by devbww** [comment]
> on Windows the MSVC2019 compiler gives error messages:
> 
> error C4996: 'strcpy': This function may be unsafe. Consider using strcpy_s instead.

OK, I'll tweak things to avoid strcpy() [although the code is actually safe].  Thanks.

> I wondered why you use different versions of strcpy

Just an historical artifact, but I'll address that too.

**Comment by devbww** [comment]
Thanks.  Let me know if that doesn't work for you.

**Comment by mireiner** [comment]
The fix works fine (MSVC2019 C4496 error messages are gone).
Thank you Bradley!
