### ISSUE TITLE
warning: unused parameter 'zone' [-Wunused-parameter]

### ISSUE THREAD

**Issue by JeffAbrahamson** [google/cctz#11]
When compiling tools/time_tool.cc, I see this warning:

    time_tool.cc:58:65: warning: unused parameter 'zone' [-Wunused-parameter]

If it is intentional not to use zone, perhaps a statement like this would at least be helpful?

    (void)zone;   // Unused for now, silence compiler warning.

**Comment by devjgm** [comment]
JFYI, I'm not ignoring this, I've just been sick. I'll be back soon. Thanks.

**Comment by devbww** [comment]
Should now be fixed.  Thanks.
