### ISSUE TITLE
Add a time_zone constructor with a std::string parameter

### ISSUE THREAD

**Issue by HenryRLee** [google/cctz#121]
Can we have a constructor for the time_zone that takes a string, so that it would call load_time_zone in the constructor?

So instead of
```
  cctz::time_zone nyc;
  cctz::load_time_zone("America/New_York", &nyc);
```
We can do
```
  cctz::time_zone nyc("America/New_York");
```

**Comment by devbww** [comment]
How would that indicate a failure to load the time zone?  Throwing an exception would be a possibility, however the API is designed to work without exceptions.

If you want to ignore loading errors, then you could write your own helper function, but I don't think we want to encourage such practices in the API.

**Comment by HenryRLee** [comment]
Would overriding the bool conversion solve this problem? One concern is this would cost extra memory for saving the boolean status.

For example:
```
if (cctz::time_zone nyc("America/New_York")) {
   //...
} else {
   // Error
}
```

**Comment by devjgm** [comment]
The problem would be that we'd be introducing the notion of an "invalid time zone". This would now be a new state that *all* code would need to handle. For example, any function that accepts a `time_point` and a `cctz::time_zone` would need to somehow handle the case where the given `tz` is "invalid". That means that all those functions would need to grow some error-handling path.

I think it's preferable to handle the case of an invalid time-zone name in a single place: When loading the time zone.

In your own code, you are welcome to define a function like:

```cc
cctz::time_zone load_zone_or_die(const std::string& name) {
  cctz::time_zone tz;
  auto loaded = cctz::load_time_zone(name, &tz);
  if (!loaded) {
    // throw an exception, or crash, or whatever you want
  } 
  return tz;
}
```

But as @devbww said, I don't think we want to provide an API like this in the CCTZ library itself.

**Comment by HenryRLee** [comment]
I understand. Thank you.

Closing the issue now.
