### ISSUE TITLE
Parse error for dates without separator

### ISSUE THREAD

**Issue by Enchufa2** [google/cctz#137]
- Parsing `"2019-09-30 2346"` with format `"%Y-%m-%d %H%M"` succeeds.
- But parsing `"20190930 2346"` with format `"%Y%m%d %H%M"` fails.

**Comment by devbww** [comment]
> parsing "20190930 2346" with format "%Y%m%d %H%M" fails.

This is working as intended.  `cctz::parse()` never assumes 4-digit years, so the `%Y` will gobble up all of `20190930`.

To deal with 4-digit, non-separated years, you'll need to use the `%E4Y` format specifier (although the best advice is to include a separator).
