### ISSUE TITLE
Build with with MS Visual Studio

### ISSUE THREAD

**Issue by SemenMartynov** [google/cctz#14]
It would be interesting for cross-platform application.

Actually, I'm already work on it and will send pull-request for this issue.

**Comment by devjgm** [comment]
Cool. You've probably found that we've already set up the code to support various sources of time zone data. For example, see https://github.com/google/cctz/blob/master/src/cctz_if.h and https://github.com/google/cctz/blob/master/src/cctz_libc.h for an example of an implementation alternative to the default 'zoninfo' data.

**Comment by SemenMartynov** [comment]
I made pull-request which allows to build the library for Windows (tested with Microsoft Visual Studio Community 2015) and use tzdata. On the Christmas holidays I'm going to make implementation of a class which will use WinAPI as a data source.

**Comment by devbww** [comment]
Hi.  Just to let you know that we're definitely interested in using the WinAPI as the time-zone data source.  Thanks.

**Comment by andreygorbachev** [comment]
Hi Semen. Are you planning to update the Makefile to work with Visual Studio 2015? Or is it going to be Bazel based?
Thanks.

**Comment by TheChuckster** [comment]
Any updates on Windows compatibility?

**Comment by devbww** [comment]
Hi Charles,

I haven't heard anything further from Semen about a cctz::TimeZoneIf implementation using Windows APIs as the data source.  And from other things I have read I wonder whether such a thing is even possible.

That said, I have heard that people are using CCTZ on Windows by linking the cctz::TimeZoneInfo implementation in src/time_zone_info (i.e., the one that reads the zoneinfo data files) after having installed the compiled zoneinfo data on their system.  Perhaps that might be a path forward for you.

**Comment by mireiner** [comment]
Hi devbww,

maybe you like to fix a small compiler warning in time_zone_info.cc.

On Windows Visual Studio 2015 Update 3 (latest final release) gives for row 132 and 142 the warning C4018: "<=": Conflict between "signed" and "unsigned".

Thank you

**Comment by devbww** [comment]
Done.  Please give it a try.  Thanks.

**Comment by mireiner** [comment]
That was fast and works. Thank you. :-)

**Comment by devbww** [comment]
I'm going to close this given that I believe our Windows builds are in good shape.

The issue of creating "a cctz::TimeZoneIf implementation using Windows APIs as the data source" remains open (or, even if that is possible).
