### ISSUE TITLE
hash support for cctz::time_point<cctz::seconds> ? 

### ISSUE THREAD

**Issue by fanxinping** [google/cctz#179]
Hi, I want to use `time_point` as index to get some data relate to this time quickly.
Below is an example.
```c++
#include <iostream>
#include <string>
#include <unordered_map>
#include "cctz/civil_time.h"
#include "cctz/time_zone.h"

int main(void) {
    cctz::time_zone nyc;
    cctz::load_time_zone("America/New_York", &nyc);

    auto moon_walk = cctz::convert(cctz::civil_second(1969, 7, 20, 22, 56, 0), nyc);
    std::unordered_map<decltype(moon_walk), std::string> map;
    map[moon_walk] = "Moon walk in NYC";
    std::cout << map[moon_walk] << std::endl;
    return 0;
}
```
This code cannot compile because `cctz::time_point<cctz::seconds>` is not hashable, so do you consider the hash support for this type?
Thanks!

**Comment by devbww** [comment]
`cctz::time_point<cctz::seconds>` is just an alias for ...
```
std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<std::int_fast64_t>>
```
That is, a standard time point using a 64-bit count of seconds on the system clock.  (BTW, note that those aliases are documented with _"Convenience aliases. Not intended as public API points."_)

You could hash such a value with something like `tp.time_since_epoch().count()`, but that is up to you.  CCTZ should not take a stance on how `std::chrono::time_point` values could/should be hashed.

**Comment by fanxinping** [comment]
Thanks for your suggestion and I will have a try.
