### ISSUE TITLE
Don't load utc in map when TimeZoneInfo::Load failed

### ISSUE THREAD

**Issue by anastasia0121** [google/cctz#18]
If some file from tzdata cannot be opened, utc time zone will loading to map. It can be problem. For example, if TZDIR has incorrect value and we change it, other (correct) rules of time zone don't loading. 
Also `Asia/Tehran: Failed to parse 'IRST-3:30IRDT,J80/0,J264/0'` message isn't clear for me. It means that the time zone was incorrect loading?

**Comment by devbww** [comment]
Hi Anastasia,

> If some file from tzdata cannot be opened, utc time zone will loading to
> map. It can be problem. For example, if TZDIR has incorrect value and we
> change it, other (correct) rules of time zone don't loading. 

TZDIR is not intended to be changed on the fly.  It should be set once (and correctly) before/at program startup.  As you observed, we will never try to reload any particular zone's tzdata, even if TZDIR does change.

> Also Asia/Tehran: Failed to parse 'IRST-3:30IRDT,J80/0,J264/0' message
> isn't clear for me. It means that the time zone was incorrect loading?

We've noticed this too, and are in the process of fixing it.  tz2016a introduced a new style of future rule that we did not support.  The good news is that it only affects Asia/Tehran in years after 2037---everything else will be fine.  So, please just ignore the warning for the time being.

Thanks.

**Comment by devbww** [comment]
>> Also Asia/Tehran: Failed to parse 'IRST-3:30IRDT,J80/0,J264/0' message
>> isn't clear for me. It means that the time zone was incorrect loading? 

> We've noticed this too, and are in the process of fixing it. tz2016a introduced a new style of future rule that we did not support. The good news is that it only affects Asia/Tehran in years after 2037---everything else will be fine. So, please just ignore the warning for the time being.

The "Asia/Tehran: Failed to parse" issue should now be fixed.
