### ISSUE TITLE
%E produces different results in OS X vs Linux

### ISSUE THREAD

**Issue by derekmauro** [google/cctz#180]
[Issue originally from https://github.com/abseil/abseil-cpp/issues/869]

Given:

```
#include <iostream>
#include <string>
#include <vector>

#include "absl/time/time.h"

int main() {
  absl::TimeZone tz;
  auto t = absl::FromTimeT(time(nullptr));
  absl::LoadTimeZone("America/New_York", &tz);
  std::cout << absl::FormatTime("%E", t, tz) << "\n";

  return 0;
}
```

In OS X the output is:

```
E
```

Whereas in Linux it is:

```
%E
```

Is this expected?

I started looking into this in the context of a test in Envoy that behaves differently across platforms when calling `absl::FormatTime("%E4n")`, see:

https://github.com/envoyproxy/envoy/pull/14494

**Comment by timparenti** [comment]
Since this matches the output of `date +"%E"` on the two platforms, this appears to come down to a difference in implementation for `strftime`.  Indeed, it seems macOS 10.14.6, for example, uses an older `strftime` from 2004.

**Comment by devbww** [comment]
I agree with the analysis of @timparenti ... the behavior of the incomplete specifier is outside the bailiwick of CCTZ.

Before I close this however, @rgs1 might I ask what you expected the `%E4n` specifier to produce?

**Comment by devbww** [comment]
I'm not sure whether @rgs1 saw this, but the ABSL issue was closed so I'll do the same here.

If there is more to discuss, please feel free to re-open.  Thanks.

**Comment by rgs1** [comment]
Thanks @devbww  -- I think we are good.
