### ISSUE TITLE
Add fraction of seconds support

### ISSUE THREAD

**Issue by wangbo223** [google/cctz#211]
Hi, I want to parse a string like "2022-01-07 11:21:59.123456 EST" into epoch mills ( or epoch micros ) but seems like cctz doesn't support fraction of seconds.
Can you add support to that please?

**Comment by devbww** [comment]
> I want to parse a string like "2022-01-07 11:21:59.123456 EST" into epoch mills ( or epoch micros )

OK, although you're going to have trouble with the "EST" bit.  In general it doesn't mean anything (is it Elbonian Summer Time?).

The preferred way to deal with this in CCTZ is just to parse "2022-01-07 11:21:59.123456" (a civil time), and tell `cctz::parse()` what `cctz::time_zone` to interpret that in.  Alternatively you could parse "2022-01-07 11:21:59.123456 -05:00" (a well-defined instant).

[Aside: `cctz::parse()` does allow a "%Z" format specifier, but, as the code says `// ignored; zone abbreviations are ambiguous`.]

> but seems like cctz doesn't support fraction of seconds.

It does.  For example,
```
  std::string fmt = "%Y-%m-%d %H:%M:%E*S";
  std::string date = "2022-01-07 11:21:59.123456";
  cctz::time_zone tz;
  cctz::load_time_zone("America/New_York", &tz);
  std::chrono::time_point<std::chrono::system_clock,
                          std::chrono::microseconds> tp;
  if (cctz::parse(fmt, date, tz, &tp)) {
    std::cout << date << " in " << tz.name() << " => "
              << tp.time_since_epoch().count() << "\n";
  }
```
produces
`2022-01-07 11:21:59.123456 in America/New_York => 1641572519123456`

**Comment by wangbo223** [comment]
Thank you, this is great.

**Comment by devbww** [comment]
> do you have any plan to add fraction of second to cctz::civil_day

Firstly, I presume you mean something more like a `civil_nanosecond` there.

But that said, no, there is no plan for subseconds.  You will have to model any sub-second part separately.
