### ISSUE TITLE
time_zone_lookup.cc line 32: _dupenv_s() wrong pointer assignment

### ISSUE THREAD

**Issue by mireiner** [google/cctz#24]
Original lines 31 and 32:
char* tz_env = nullptr;
_dupenv_s(*tz_env, nullptr, "TZ"); // wrong first argument is a pointer

Should be corrected to:
char* tz_env = nullptr;
_dupenv_s(&tz_env, nullptr, "TZ"); // corrected first argument is a reference

Look at Microsoft MDSN for _dupenv_s documentation and example code:
https://msdn.microsoft.com/en-us/library/ms175774.aspx

**Comment by devbww** [comment]
Thanks for the report and fix.  Your help is much appreciated.
