### ISSUE TITLE
MinGW compiler errors on Windows

### ISSUE THREAD

**Issue by mireiner** [google/cctz#26]
_dupenv_s()
_get_timezone()
_get_tzname()

are Microsoft Visual Studio compiler functions only (as far as I know). The MinGW compiler (and probably any other compiler) doesn't know these funtions.

So for the obove mentioned functions the macros
#if defined(_WIN32) || defined(_WIN64)
should be changed to
#if defined (_MSC_VER) // Microsoft Compiler only

in the files time_zone_info.cc, time_zone_libc.cc and time_zone_lookup.cc.

**Comment by devbww** [comment]
So changed.  Thanks.
