### ISSUE TITLE
Help!!! How to get specific current timezone name?

### ISSUE THREAD

**Issue by superdiaodiao** [google/cctz#272]
When I use this method, 
**cctz::local_time_zone().name()**, 
and it returns '/etc/localtime',
so is there a proper way to return the correct timezone name including a city name when I use cctz?

**Comment by devbww** [comment]
> is there a ... way to return the correct timezone name ... when I use cctz[::local_time_zone()]?

In general, the answer is no.

You mention that it returns *"/etc/localtime"*, which means cctz is using that file to obtain the local tzdata.  [Unfortunately](https://github.com/google/cctz/blob/1261fab0af89c3c1f4e1e6b6b354e0748a888428/src/time_zone_impl.h#L44), tzdata files do not include the name of the zone that produced them.  Sometimes /etc/localtime is a symlink to a named tzdata file, so you might discover the name by looking at the link target name.  Sometimes /etc/localtime is a hard link to a named tzdata file, so you might discover the name by searching for the inode number.  And sometimes /etc/localtime is just a copy of a named tzdata file, so you'd have to resort to searching by content.  All of these things are outside the purview of `local_time_zone()`.

If I had my time again, I'd probably omit `cctz::time_zone::name()` altogether.

**Comment by superdiaodiao** [comment]
> 

Thanks for your reply. 
You mean that no matter how I set the timezone of my machine, I can only get the file name if I just use the **local_time_zone().name()** method?

If so, how can I search for the inode number or resort to searching by content, just like you said?
Any concrete step will be appreciated.

**Comment by superdiaodiao** [comment]
> 

Thanks for your reply.
You mean that no matter how I set the timezone of my machine, I can only get the file name if I just use the local_time_zone().name() method?

If so, how can I search for the inode number or resort to searching by content, just like you said?
Any concrete step will be appreciated.

**Comment by superdiaodiao** [comment]
> > is there a ... way to return the correct timezone name ... when I use cctz[::local_time_zone()]?
> 
> In general, the answer is no.
> 
> You mention that it returns *"/etc/localtime"*, which means cctz is using that file to obtain the local tzdata.  [Unfortunately](https://github.com/google/cctz/blob/1261fab0af89c3c1f4e1e6b6b354e0748a888428/src/time_zone_impl.h#L44), tzdata files do not include the name of the zone that produced them.  Sometimes /etc/localtime is a symlink to a named tzdata file, so you might discover the name by looking at the link target name.  Sometimes /etc/localtime is a hard link to a named tzdata file, so you might discover the name by searching for the inode number.  And sometimes /etc/localtime is just a copy of a named tzdata file, so you'd have to resort to searching by content.  All of these things are outside the purview of `local_time_zone()`.
> 
> If I had my time again, I'd probably omit `cctz::time_zone::name()` altogether.

Thanks for your reply.
You mean that no matter how I set the timezone of my machine, I can only get the file name if I just use the local_time_zone().name() method?

If so, how can I search for the inode number or resort to searching by content, just like you said?
Any concrete step will be appreciated.

**Comment by devbww** [comment]
> You mean that no matter how I set the timezone of my machine, I can only get the file name if I just use the local_time_zone().name() method?

If you depend on /etc/localtime to supply the tzdata for `local_time_zone()`, then you will only ever get *"/etc/localtime"* from `local_time_zone().name()`.

[Aside: I would typically recommend not depending on the machine's idea of the local timezone (indeed, set it to UTC), but rather to set `${TZ}` in your environment to set your process's idea of the local timezone.  Then `local_time_zone().name()` will return the value of `${TZ}`.]

> how can I search for the inode number or resort to searching by content, just like you said?

- If /etc/localtime is a symlink ...
```
$ readlink /etc/localtime
/usr/share/zoneinfo/America/New_York
```
- If /etc/localtime is a hard link (or symlink) ...
```
$ find /usr/share/zoneinfo -inum $(stat -L -c %i /etc/localtime) -print
/usr/share/zoneinfo/America/New_York
```
- If /etc/localtime is a copy (or hardlink or symlink) ...
```
$ find /usr/share/zoneinfo -type f -exec cmp -s /etc/localtime {} \; -print
/usr/share/zoneinfo/America/New_York
```

**Comment by superdiaodiao** [comment]
> > You mean that no matter how I set the timezone of my machine, I can only get the file name if I just use the local_time_zone().name() method?
> 
> If you depend on /etc/localtime to supply the tzdata for `local_time_zone()`, then you will only ever get *"/etc/localtime"* from `local_time_zone().name()`.
> 
> [Aside: I would typically recommend not depending on the machine's idea of the local timezone (indeed, set it to UTC), but rather to set `${TZ}` in your environment to set your process's idea of the local timezone.  Then `local_time_zone().name()` will return the value of `${TZ}`.]
> 

oh, I see.

> > how can I search for the inode number or resort to searching by content, just like you said?
> 
> - If /etc/localtime is a symlink ...
> ```
> $ readlink /etc/localtime
> /usr/share/zoneinfo/America/New_York
> ```
> - If /etc/localtime is a hard link (or symlink) ...
> ```
> $ find /usr/share/zoneinfo -inum $(stat -L -c %i /etc/localtime) -print
> /usr/share/zoneinfo/America/New_York
> ```
> - If /etc/localtime is a copy (or hardlink or symlink) ...
> ```
> $ find /usr/share/zoneinfo -type f -exec cmp -s /etc/localtime {} \; -print
> /usr/share/zoneinfo/America/New_York
> ```
> 
Thanks a lot, this is helpful too

**Comment by devbww** [comment]
> is it a good idea to do these in c++ code?

I don't think so.

> Or do we have a better way?

I don't think so either.  I'm not sure of your use case, but in general I would recommend against using `local_time_zone()` in all but informational contexts, and never depending upon its name.

**Comment by superdiaodiao** [comment]
> > is it a good idea to do these in c++ code?
> 
> I don't think so (at least not within CCTZ).
> 
> > Or do we have a better way?
> 
> I don't think so either.  I'm not sure of your use case, but in general I would recommend against using `local_time_zone()` in all but informational contexts, and never depending upon its name.

OK, what a pity

**Comment by devbww** [comment]
> OK, what a pity

Perhaps.  Your options seem to be to justify your use case enough to convince the tz maintainers to update the tzfile format to include the generating zone name, and/or convince all platforms to support a mechanism to provide the local timezone name instead of just the local timezone data.
