### ISSUE TITLE
Android compatibility 

### ISSUE THREAD

**Issue by gcamp** [google/cctz#28]
I'm looking into adding Android compatibility. Apart from a few build issues that can be fixed easily, it seems Android doesn't have the same timezone file layout as other systems. 

Instead of subfolders in `/system/usr/share/zoneinfo/`, there's one big file that looks like it's the same format as other timezone files but I can't confirm that's the case. 

Any idea how to work around or fix this problem? Thanks!

(BTW the library works great on iOS)

**Comment by devbww** [comment]
Hi Guillaume,

Re the one, big file on Android, are you referring to something like `ANDROID_DATA/misc/zoneinfo/current/tzdata` or `ANDROID_ROOT/usr/share/zoneinfo/tzdata`?  If so, my understanding is that this is an aggregation of all the normal tzdata files along with an index by zone name.

Unfortunately, it looks like there is no API to access this data.  Its shape and accessing code are hidden inside the C library, so it will take us a little while to figure out what to do in that environment.  Sorry.

If you learn anything in the meantime we will be happy to hear about it.  Thanks.

**Comment by TheChuckster** [comment]
Any progress on this? Looking forward to using CCTZ with Android as well in my game written in C++ using the NDK.

One idea for now until a "real solution" arrives is to stash a compatible zoneinfo file layout inside my APK using the asset system and then hook into the AssetManager using JNI calls.

Such a shame Android is this much of a mess.

**Comment by devbww** [comment]
Hi Chuck,

No, no progress as yet.

If you open [http://android.googlesource.com/platform/bionic/+/master/libc/tzcode/localtime.c](http://android.googlesource.com/platform/bionic/+/master/libc/tzcode/localtime.c) you'll be able to see the "open_tzdata" calls it would be nice to have access to.  Then we could teach cctz::TimeZoneInfo::Load(const std::string&) how to get a FILE* positioned correctly for the particular zone name (and how to map "localtime" to a real zone name).

If I cannot manage to convince the Android developers to expose those interfaces, we should just be able to reimplement them within CCTZ.

But yes, if you can manage to get access to a standard zoneinfo file layout, you should just be able to point cctz::TimeZoneInfo at it (look for TZDIR in src/time_zone_info.cc).

**Comment by devbww** [comment]
Sorry for the delay Chuck, but the changes I outlined above to read the Android tzdata file and to obtain the local time-zone name from within CCTZ are now committed.  Please give them a try and close this issue if all looks good.  Thanks.

**Comment by devbww** [comment]
And Guillaume too, of course.

**Comment by gcamp** [comment]
Everything works great for us on Android!
