### ISSUE TITLE
Do you have correctness guarantee of time BCE?

### ISSUE THREAD

**Issue by zclllyybb** [google/cctz#280]
I meet a bug, not very sure it's about cctz. when I do timezone convert of a timepoint long before BC, I got different result in different compilation environment . and I've checked it that it has no overflow of min-max of time_point.

**Comment by devbww** [comment]
If you have code for a simple reproduction of the issue, and display its results in those different environments, I might be able to help figure out what's going on.  Please ensure that you are using the same tzdata in each case though.

As to the correctness-guarantee question, the intent is certainly that cctz should return the same results given the same inputs in any environment, but there may be platform variations in `std::chrono`.  How far in the past are we talking here?

**Comment by devbww** [comment]
No response, so I'll assume this was resolved externally.
