### ISSUE TITLE
How to specific the tzfiles' dir?

### ISSUE THREAD

**Issue by zclllyybb** [google/cctz#287]
in FAQ it mentioned 
> The CCTZ time-zone library uses the compiled [IANA time-zone database](https://www.iana.org/time-zones) files that exist on the system. These are typically found in /usr/share/zoneinfo or in the directory named in the TZDIR environment variable.

In our circumstances we want the ability to specific tzdb's dir when start our application. Does cctz support this now?

If now, where is the context I should modify?

**Comment by zclllyybb** [comment]
well, I found it in `time_zone_info.cc`. But I'd still like to know when will we load the tzfiles into memory?

**Comment by devbww** [comment]
>> These are typically found in /usr/share/zoneinfo or in the directory named in the TZDIR environment variable.
>
> In our circumstances we want the ability to specific tzdb's dir when start our application. Does cctz support this now?

You would do that by setting, as mentioned, the TZDIR environment variable.

> well, I found it in `time_zone_info.cc`. But I'd still like to know when will we load the tzfiles into memory?

I'm not sure I understand the question, so I'll just say that the tzdata file for a zone is loaded when you call `load_time_zone()` for that zone.
