### ISSUE TITLE
Linux <-> OSX mismatch (internal overflow?)

### ISSUE THREAD

**Issue by Siesh1oo** [google/cctz#29]
Hi, this small test program gives different results on OS X vs. Linux (both gcc-6.1.1 and llvm-clang++-3.6):

```
#include <chrono>
#include <iostream>
#include <time_zone.h>

int main (int argc, char ** argv) {
	std::chrono::system_clock::time_point tp;
	auto date = "18 April 2275";
	cctz::parse("%d %B %Y", date, cctz::local_time_zone(), &tp);
	auto d = cctz::convert(tp, cctz::local_time_zone());
	std::cout << date << " <-> " << d << std::endl;
	return 0;
}

// output OSX/64bit:   18 April 2275 <-> 2275-04-18T00:00:00
// output Linux/64bit: 18 April 2275 <-> 1690-09-26T23:18:55
```

The bug is exposed when verifying the Australian Astronomical Society Easter Dates against Knuth's Easter Date algorithm.

**Comment by Siesh1oo** [comment]
Note: this is indeed an overflow "under the hood", exceeding the limits of system_clock::time_point. Possibly cctz::parse() should return false, and/or throw an exception?

```
std::chrono::system_clock::time_point::min(): 1677-09-21T01:06:12
std::chrono::system_clock::time_point::max(): 2262-04-12T01:47:16
```

**Comment by devjgm** [comment]
Sorry for the delay.  Thanks for the simple repro case. I think Brad was looking into this and should get back with you shortly.

**Comment by devbww** [comment]
> Note: this is indeed an overflow "under the hood", exceeding the limits of system_clock::time_point.

Yes.  It looks like the Linux system_clock::time_point is based on a signed 64-bit count of nanoseconds, which means it maxes out at 2262-04-11T19:47:16.854775807+0000.

> Possibly cctz::parse() should return false, and/or throw an exception?

Yes, I'll look into something like that.  In the meantime, if you only require second resolution I would suggest working with std::chrono::time_point<std::chrono::system_clock, cctz::sys_seconds> (a.k.a. cctz::time_point<cctz::sys_seconds>) instead of std::chrono::system_clock::time_point.

**Comment by devbww** [comment]
It turns out that it is problematic for cctz::parse() to determine whether the value it successfully parsed is representable in the output std::chrono::time_point<std::chrono::system_clock, D> type.  Therefore it seems best to leave the behavior there unspecified.

In general it looks like the caller will just have at be aware of what time values are representable in their chosen Duration type.  Being familiar with the value of ...

`cctz::format("%F %T %z", std::chrono::time_point<std::chrono::system_clock, D>::max(), tz)`

on your platforms of choice would probably avoid some surprises.  In particular, it appears that std::chrono::system_clock::time_point on Linux uses std::chrono::nanoseconds for D while OSX uses std::chrono::microseconds (both with 64-bit Reps).

**Comment by Siesh1oo** [comment]
Sorry for answering to the closed issue.

How exactly ought one interpret "the caller will just have at be aware of what time values are representable in their chosen Duration type"? cctz::parse() is operating on arbitrary runtime/user input, without parsing independently (and then there is no need to call cctz::parse()), there seems no easy way to check user input...

One option thinkable to perform user input error checking could be conceived by always doing the reverse operation (parse(); format()), and check equivalence of input. Then again, if this has to be done always to ensure validate success of calling parse(), shouldn't it belong into cctz::parse() itself?

Asking for clarification: is my understanding correct that the problems in error checking cctz::parse() are caused by the underlying call to strptime() of the operating system? Wouldn't it be possible to borrow&fork some strptime()-implementation with permissive license into the cctz source tree and modify it appropriately to return the proper status code?

Thinking about it, might it be possible to overcome this issue by using a custom cctz::time_point representation instead of aliasing std::chrono::system_clock, with high resolution both for the epoch second part and the sub-second fraction? This way cctz could provide true OS abstraction and well-defined portable behavior, and possible similar issues in other functions could be minimized, as the space of required test cases for overflows is much more restricted when inputs variables are restricted to known bounds.

**Comment by devbww** [comment]
Hi Siesh1oo,

> How exactly ought one interpret "the caller will just have at be aware of what time values are representable in their chosen Duration type"? cctz::parse() is operating on arbitrary runtime/user input, without parsing independently (and then there is no need to call cctz::parse()), there seems no easy way to check user input...

For example, if you're parsing with "%d %B %Y" and you want to maximize the range that you can represent, then passing a std::chrono::system_clock::time_point is probably not a good choice.  Using std::chrono::time_point&lt;std::chrono::system_clock, std::chrono::seconds&gt; instead would guarantee support for years up to at least 3058.

> Asking for clarification: is my understanding correct that the problems in error checking cctz::parse() are caused by the underlying call to strptime() of the operating system? Wouldn't it be possible to borrow&fork some strptime()-implementation with permissive license into the cctz source tree and modify it appropriately to return the proper status code?

No, I don't think it has anything to do with strptime().  cctz::parse() successfully parses your time ... it just cannot represent the parsed value in the time_point you provided.  It's like, for example, trying `int8_t v = atoi("1000")` ... it just doesn't fit.

> Thinking about it, might it be possible to overcome this issue by using a custom cctz::time_point representation instead of aliasing std::chrono::system_clock, with high resolution both for the epoch second part and the sub-second fraction? This way cctz could provide true OS abstraction and well-defined portable behavior, and possibly similar issues in other functions could be minimized, as the space of required test cases for overflows is much more restricted when inputs variables are restricted to known bounds.

cctz::parse() effectively already does this internally.  However, the last part---passing such a chrono::time_point type to cctz::parse()---is up to you.

cctz could provide a time_point type with nanosecond resolution and a range covering the age of the universe if there was a standard integer type longer than 64 bits.  You could do it today if you have such an integer type on your platform.

**Comment by Siesh1oo** [comment]
With respect to

> guarantee support for years up to at least 3058.

I am yet wondering how it would be possible to validate user input, i.e. guarantee that for a given input the correct result is returned, and invalid (overflowing) input strings are reliably rejected. In particular, following your analogy:

> It's like, for example, trying int8_t v = atoi("1000") ... it just doesn't fit.

atoi(**endptr) will set endptr to the end of the parsed string, so the error check can see if this is pointing to the terminating byte or a whitestring/separation character and bail out if necessary. Functions like strtol() will even return an error and set errno=ERANGE in case of overflow.

However, in the case of cctz::parse() we know the allowed range (i.e. time_point::min() .. time_point::max()), but how do we check whether strings parsed at runtime actually fit this range?

Aliasing correct and invalid inputs to sometimes right, sometimes wrong outputs seems an unfortunate mechanism.

**Comment by devbww** [comment]
I'm making some changes that will allow my next response to be very specific.  Hopefully that will help you provide such a guarantee.  It will take a little time however.

In the meantime ...

>> It's like, for example, trying int8_t v = atoi("1000") ... it just doesn't fit.
> 
> Functions like strtol() will even return an error and set errno=ERANGE in case of overflow.

But strtol() doesn't overflow on "1000".  It is only when you, the user, try to stuff the result into an int8_t that things go wrong.

Perhaps you might be able to help figure out how, if given ...

`std::chrono::time_point<C, D1> tp1 = ...;`

we can determine whether ...

`std::chrono::time_point<C, D2> tp2 = std::chrono::time_point_cast<D2>(tp1);`

produces overflow (or some other undesirable result).

**Comment by Siesh1oo** [comment]
Please tell me if I misunderstand the issue, but I understand this as _"parse() needs to know the exact type of the passed time_point, in order to be able to report if the limits of this particular type are exceeded"_?

In the case of strtol(), atoi() etc the type is known (specified by function signature, overflow detection works if and only if the type matches the function signature, i.e. 'long' for strtol(), 'int' for atoi()). As the return type of cctz::parse() is passed as by-reference argument, only these conventions would be valid:

- either only cctz::system_clock::time_point is a valid return type passed as argument, or
- or cctz::parse() is actually wrapping the implementation cctz::internal_parse() and detecting range limits at compile time, such as this:

```
template <typename T>
inline bool parse(const std::string& fmt, const std::string& input,
                  const time_zone& tz, T* tpp) {
    return parse_internal(fmt, input, tz, tpp, T::min(), T::max());
}

template <typename D> bool cctz::parse_internal (const std::string& fmt, const std::string& input,
                  const time_zone& tz, time_point<D>* tpp, const time_point<D> & tpp_min, const time_point<D> & tpp_max) {
    /* ... do actual parsing and check against overflowing limits of range tpp_min..tpp_max */
}
```

Would this make sense and is this targeting the actual problem, or am I misunderstanding the deeper issue?

**Comment by devbww** [comment]
The current committed state of ...

```
template <typename D>
bool parse(const std::string& fmt, const std::string& input,
           const time_zone& tz, time_point<D>* tpp);
```

now allows me to guarantee that the internal code will correctly parse times representable as signed 64-bit counts of seconds from the Unix epoch, plus sub-seconds of femtosecond granularity.

The conversion of that time into the `time_point<D>` provided by the caller, however, might still fail due to range overflow and without producing a false result.  I'm interested in trying to fix that.

So, in response to your "_`parse()` needs to know the exact type of the passed time_point, in order to be able to report if the limits of this particular type are exceeded_" I would say, `parse()` does know that exact type, but I don't (yet) know how to determine if its limits have been exceeded by the value parsed.

**Comment by Siesh1oo** [comment]
Wouldn't wrapping the time_point<D> cast (as provided by the caller) into a separate function as outlined previously solve the problem – the parsed time point (as 64-bit count) must not exceed the limits defined by time_point<D>::min() and time_point<D>::max() in the wrapper call above?

**Comment by devbww** [comment]
Give it a try.  I hit problems with the `std::chrono` implementation which I have not yet determined how to work around.  For example, given ...
```
auto tp1 = cctz::time_point<cctz::sys_seconds>::max();
auto tp2 = std::chrono::system_clock::time_point::max();
```
my `std::chrono` (glibc) says that `tp1 < tp2` despite the fact that the values are ...
```
tp1 = 292277026596-12-04 15:30:07 +00:00
tp2 = 2262-04-11 23:47:16 +00:00
```
(signed 64-bit counts of seconds and nanoseconds respectively).

**Comment by Siesh1oo** [comment]
Casting to the higher-capacity type and doing the comparison in the higher-capacity domain works:

```
$ cat /tmp/t.cc 
#include <chrono>
#include <time_zone.h>
#include <iostream>

int main (int argc, char ** argv) {
	auto tp1 = cctz::time_point<cctz::sys_seconds>::max();
	auto tp2 = std::chrono::system_clock::time_point::max();
	std::cout << "tp1 < tp2 == " << (tp1 < tp2) << std::endl;
	std::cout << "tp1 < std::chrono::time_point_cast<decltype(tp1)::duration>(tp2) == " << (tp1 < std::chrono::time_point_cast<decltype(tp1)::duration>(tp2)) << std::endl;
	return 0;
}

$ g++ -o /tmp/t /tmp/t.cc -g -Wall -O0 -std=c++11 && /tmp/t
tp1 < tp2 == 1
tp1 < std::chrono::time_point_cast<decltype(tp1)::duration>(tp2) == 0
```

**Comment by devbww** [comment]
How do you determine which is the higher-capacity type for an arbitrary time_point<D>?

**Comment by Siesh1oo** [comment]
One can use the limits and division ratio of time_point::duration to compare the capacities. But see [*]

```
$ cat /tmp/t.cc 

#include <cassert>
#include <chrono>
#include <limits>
#include <typeinfo>
#include <iostream>

template <typename TP1, typename TP2> void compare_capacity (const TP1 & tp1, const TP2 & tp2) {
	std::cout << "TP1::duration::period::num : " << TP1::duration::period::num << std::endl;
	std::cout << "TP1::duration::period::den : " << TP1::duration::period::den << std::endl;
	std::cout << "typeid(typename TP1::duration::rep).name() : " << typeid(typename TP1::duration::rep).name() << std::endl; 
	std::cout << "std::numeric_limits<typename TP1::duration::rep>::min() : " << std::numeric_limits<typename TP1::duration::rep>::min() << std::endl;
	std::cout << "std::numeric_limits<typename TP1::duration::rep>::max() : " << std::numeric_limits<typename TP1::duration::rep>::max() << std::endl;
	typename TP1::duration::rep TP1capacity_min = (std::numeric_limits<typename TP1::duration::rep>::min() / TP1::duration::period::den) * TP1::duration::period::num;
	typename TP1::duration::rep TP1capacity_max = (std::numeric_limits<typename TP1::duration::rep>::max() / TP1::duration::period::den) * TP1::duration::period::num;
	/* centered around de-facto standard epoch 1970-01-01 */
	std::cout << "TP1capacity_min : " << TP1capacity_min << " seconds (" << (TP1capacity_min / (3600.0 * 24 * 265.25)) << " years)" << std::endl;
	std::cout << "TP1capacity_max : " << TP1capacity_max << " seconds (" << (TP1capacity_max / (3600.0 * 24 * 265.25)) << " years)" << std::endl;
	std::cout << "TP2::duration::period::num : " << TP2::duration::period::num << std::endl;
	std::cout << "TP2::duration::period::den : " << TP2::duration::period::den << std::endl;
	std::cout << "typeid(typename TP2::duration::rep).name() : " << typeid(typename TP2::duration::rep).name() << std::endl; 
	std::cout << "std::numeric_limits<typename TP2::duration::rep>::min() : " << std::numeric_limits<typename TP2::duration::rep>::min() << std::endl;
	std::cout << "std::numeric_limits<typename TP2::duration::rep>::max() : " << std::numeric_limits<typename TP2::duration::rep>::max() << std::endl;
	typename TP2::duration::rep TP2capacity_min = (std::numeric_limits<typename TP2::duration::rep>::min() / TP2::duration::period::den) * TP2::duration::period::num;
	typename TP2::duration::rep TP2capacity_max = (std::numeric_limits<typename TP2::duration::rep>::max() / TP2::duration::period::den) * TP2::duration::period::num;
	/* centered around de-facto standard epoch 1970-01-01 */
	std::cout << "TP2capacity_min : " << TP2capacity_min << " seconds (" << (TP2capacity_min / (3600.0 * 24 * 265.25)) << " years)" << std::endl;
	std::cout << "TP2capacity_max : " << TP2capacity_max << " seconds (" << (TP2capacity_max / (3600.0 * 24 * 265.25)) << " years)" << std::endl;
	/* naive comparison assumes same-signedness of TP1::duration::rep and TP2::duration::rep */
	assert(std::is_signed<typename TP1::duration::rep>() == std::is_signed<typename TP1::duration::rep>());
	std::cout << "TP1capacity < TP2capacity : " << (TP1capacity_max < TP2capacity_max) << std::endl;
	/* But actually, the std::chrono::time_point comparison operator should do this correctly? What is required by the C++ standard? */
}

int main (int argc, char ** argv) {
	std::chrono::system_clock::time_point tp1;
	std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<std::int_fast64_t> > tp2;
	compare_capacity(tp1, tp2);
	return 0;
}

$ g++ -g -Wall -O0 /tmp/t.cc -o /tmp/t && /tmp/t
TP1::duration::period::num : 1
TP1::duration::period::den : 1000000000
typeid(typename TP1::duration::rep).name() : l
std::numeric_limits<typename TP1::duration::rep>::min() : -9223372036854775808
std::numeric_limits<typename TP1::duration::rep>::max() : 9223372036854775807
TP1capacity_min : -9223372036 seconds (-402.458 years)
TP1capacity_max : 9223372036 seconds (402.458 years)
TP2::duration::period::num : 1
TP2::duration::period::den : 1
typeid(typename TP2::duration::rep).name() : l
std::numeric_limits<typename TP2::duration::rep>::min() : -9223372036854775808
std::numeric_limits<typename TP2::duration::rep>::max() : 9223372036854775807
TP2capacity_min : -9223372036854775808 seconds (-4.02458e+11 years)
TP2capacity_max : 9223372036854775807 seconds (4.02458e+11 years)
TP1capacity < TP2capacity : 1
```

[*] Actually, the libc return value of the chrono::time_point comparison operator looks suspicious. If done 'intuitively right', the comparison should operate automagically in the domain of the higher-resolution time point object (just as the capacity comparison above). What does the standard require? I'll post a follow-up after digging a bit deeper

**Comment by Siesh1oo** [comment]
Time point comparison operators properly operate in the domain of the greater-capacity-type. But they compare tp::count(), not tp::time_since_epoch(), ignoring the division ratio of the clock period:

```
/* From /usr/include/c++/6.2.1/chrono: */
    template<typename _Rep1, typename _Period1,
             typename _Rep2, typename _Period2>
      constexpr bool
      operator<(const duration<_Rep1, _Period1>& __lhs,
                const duration<_Rep2, _Period2>& __rhs)
      {
        typedef duration<_Rep1, _Period1>                       __dur1;
        typedef duration<_Rep2, _Period2>                       __dur2;
        typedef typename common_type<__dur1,__dur2>::type       __ct;
        return __ct(__lhs).count() < __ct(__rhs).count();
      }
```

So the result of comparing two time points with different periods will quite probably not be what one expects naively.

Instead of using the naive compare operator, we need sometime like:

```
$ cat /tmp/t.cc 

#include <cassert>
#include <chrono>
#include <iostream>

template <typename TP1, typename TP2>
bool compare_timepoints_in_same_domain (const TP1 & tp1, const TP2 & tp2) {
	auto tp1_seconds_since_epoch = tp1.time_since_epoch().count() * TP1::period::num / TP1::period::den;
	auto tp2_seconds_since_epoch = tp2.time_since_epoch().count() * TP2::period::num / TP2::period::den;
	std::cout << "tp1_seconds_since_epoch : " << tp1_seconds_since_epoch << std::endl;
	std::cout << "tp2_seconds_since_epoch : " << tp2_seconds_since_epoch << std::endl;
	return tp1_seconds_since_epoch < tp2_seconds_since_epoch;
}

int main (int argc, char ** argv) {
	auto cmp = compare_timepoints_in_same_domain(std::chrono::system_clock::time_point::max(), std::chrono::time_point<std::chrono::system_clock, std::chrono::duration<std::int_fast64_t>>::max());
	std::cout << "cmp : " << cmp << std::endl;
	return 0;
}

$ g++ -g -Wall -O0 /tmp/t.cc -o /tmp/t && /tmp/t
tp1_seconds_since_epoch : 9223372036
tp2_seconds_since_epoch : 9223372036854775807
cmp : 1
```

**Comment by Siesh1oo** [comment]
I just checked that the libc++ implementation matches the standard, both the implementation of operator<(time_point, time_point) and the underlying operator<(duration, duration) quoted above implement pretty literally whats required in N3797 §20.12.6.6 and §20.12.5.6, so it looks about right (but not what is needed when comparing time points with different periods).

**Comment by Siesh1oo** [comment]
Another comment regarding a potential overflow. as the tp::max() method will return a rather large value, an overflow is possible+likely if tp::period::num is > 1. Thus division should by den should happen first, before multiplying by num:

```
	auto tp1_seconds_since_epoch = (tp1.time_since_epoch().count() / TP1::period::den) * TP1::period::num;
	auto tp2_seconds_since_epoch = (tp2.time_since_epoch().count() / TP2::period::den) * TP2::period::num;
```
