### ISSUE TITLE
Makefile install rule broke in commit 5c54e2a1da81d6def6a720df16b8570341a5a90a

### ISSUE THREAD

**Issue by Siesh1oo** [google/cctz#31]
This commit 

[https://github.com/google/cctz/commit/2e83ff2e47dab211eedf4daa508c34b52cdcc7af](url)

introduced calls to command cp with the '-d' flag in several install targets, this is a GNU extension not supported on non-GNU POSIX systems (e.g. OS X and BSD). A portable solution might use the 'install' command (non-POSIX but available on both BSD and GNU systems) to create directories and copy files, or restrict 'cp' usage to the POSIX option subset?

**Comment by Siesh1oo** [comment]
The same commit introduced linker flag "-Wl,-soname,libcctz.so.2", a linux-only thing (related to GNU automake/autoconf/libtool library versioning?) 

Maybe the Makefile could wrap adding this option like this?

```
ifeq ($(shell uname),Linux)
        LDFLAGS += -Wl,-soname,$(CCTZ_SHARED_SONAME)
endif
```

**Comment by devbww** [comment]
@mattyclarkson : I'm thinking of removing the new shared-library stuff as too Linux specific, or trying to make it totally optional somehow, or separating it out into a separate "Makefile.linux".  Any thoughts?

**Comment by mattyclarkson** [comment]
We should definitely be using `install` rather than `cp` to install the files. The easiest thing would be to remove the `install_shared_lib` from the `install` target dependencies and the building of the shared library would be completely optional then. Once it is optional we could work on making sure it supports building shared libraries on each POSIX platform?

With respect to the `soname` I understand that this is still supported on BSD from the [man page](https://www.freebsd.org/cgi/man.cgi?ld(1)), it supports `-soname` argument. I'm by no means an expert on that or MacOSX though

**Comment by Siesh1oo** [comment]
If Linux-specific stuff is encapsulated in a ifeq-uname=Linux-endif block, everything should be fine.

In general it would be nice to have separate targets for static and shared libraries, as shared builds tend to cause some headache by introducing many more variables (versions, shared-object location, implicit ld-rules, environment variables) without necessarily providing much benefit if libraries are tiny.

'make shared' and 'make shared-install' in addition to 'make static' and 'make static-install', and 'make all' as alias to 'make static shared', 'make install' aliasing to 'make static-install shared-install' should be fine for the vast majority of use cases while needing only minimal changes to the current code.

All that said, the current state is quite OK-ish and definitely usable if the 'cp -d' flag and '-soname' issues are resolved (done locally as outlined above, working just fine on OS X and Linux).

**Comment by Siesh1oo** [comment]
> With respect to the soname I understand that this is still supported on BSD from the man page, it supports -soname argument. I'm by no means an expert on that or MacOSX though

This depends on the OS version, on recent OS X both GNU gcc (macports) and llvm/clang use -install-name for shared object versioning. NetBSD and FreeBSD use -soname. On recent vanilla OS X versions, gcc is an alias to llvm/clang, so that the latter option has to be used.

Note that -Wl,-rpath,-$(DESTDIR)/lib might improve robustness as cctz references external libraries, in order to enforce consistency between header and library version at build time and run time.

That said, as shared library versioning is not mandatory, building with '-shared' and without versioning or forced rpath works just fine on Linux, OS X and BSD flavors.

**Comment by devbww** [comment]
OK ... I've simplified things.  Use install instead of mkdir/cp.  Remove shared-library versioning, and make "install_shared_lib" independent of "install".

Let me know if that is working in your environments, and then we can take things from there.  Thanks.

**Comment by mattyclarkson** [comment]
@devbww looks good. Would it be possible to add an empty `${CCTZ_SONAME_ARG}` (or similar) so I could do `CCTZ_SONAME_ARG=-Wl,-soname,libcctz.so.2 CCTZ_SHARED_LIB=libcctz.so.2.0 make libcctz.so.2.0`? I can handle the generation of the symlinks in my build script. @Siesh1oo sorry for breaking things :(

**Comment by Siesh1oo** [comment]
@mattyclarkson, don't mind, that's fine, every improvement is worthwhile!

**Comment by Siesh1oo** [comment]
Hello @mattyclarkson,

regarding symbolic links:

> I can handle the generation of the symlinks in my build script.

No need to do this manually, ldconfig will do this for you, and re-build the library cache. You find a nice explanation in this blog: [https://grahamwideman.wordpress.com/2009/02/09/the-linux-loader-and-how-it-finds-libraries/](url)

**Comment by mattyclarkson** [comment]
@Siesh1oo thanks :smile:

**Comment by devbww** [comment]
> Would it be possible to add an empty ${CCTZ_SONAME_ARG} (or similar)

Done with "SHARED_LDFLAGS = -shared" so you can override to get whatever you want when linking the shared library.

Closing.

**Comment by Siesh1oo** [comment]
@devbww @mattyclarkson 

I am sorry to re-open this issue again. The BSD/OSX version of install does not have a '-t' flag (not sure why the GNU version has this, as the 3rd calling convention '-t' listed is redundant to the 2nd listed in the man page). Here are the man pages for reference:

> https://linux.die.net/man/1/install
> https://www.freebsd.org/cgi/man.cgi?query=install

This patch applied locally solved the issue:

```
$ git diff
diff --git a/Makefile b/Makefile
index d33ceea..6c7816d 100644
--- a/Makefile
+++ b/Makefile
@@ -80,15 +80,15 @@ install: install_hdrs install_lib
 
 install_hdrs: $(CCTZ_HDRS)
        $(SUDO) $(INSTALL) -d $(DESTDIR)$(PREFIX)/include
-       $(SUDO) $(INSTALL) -m 644 -p -t $(DESTDIR)$(PREFIX)/include $?
+       $(SUDO) $(INSTALL) -m 644 -p $? $(DESTDIR)$(PREFIX)/include
 
 install_lib: $(CCTZ_LIB)
        $(SUDO) $(INSTALL) -d $(DESTDIR)$(PREFIX)/lib
-       $(SUDO) $(INSTALL) -m 644 -p -t $(DESTDIR)$(PREFIX)/lib $?
+       $(SUDO) $(INSTALL) -m 644 -p $? $(DESTDIR)$(PREFIX)/lib
 
 install_shared_lib: $(CCTZ_SHARED_LIB)
        $(SUDO) $(INSTALL) -d $(DESTDIR)$(PREFIX)/lib
-       $(SUDO) $(INSTALL) -m 644 -p -t $(DESTDIR)$(PREFIX)/lib $?
+       $(SUDO) $(INSTALL) -m 644 -p $? $(DESTDIR)$(PREFIX)/lib
 
 clean:
        @$(RM) $(EXAMPLES:=.dSYM) $(EXAMPLES:=.o) $(EXAMPLES:=.d) $(EXAMPLES)
```

**Comment by mattyclarkson** [comment]
For reference, the following command builds the shared library correctly for Linux. You may want to add it to the Makefile documentation as an example. Might stop people raising issues in the future.

`make -C build -f ../Makefile SRC=../ -j `nproc` install_hdrs install_shared_lib SHARED_LDFLAGS='-shared -Wl,-soname,libcctz.so.2' CCTZ_SHARED_LIB=libcctz.so.2.0`

**Comment by devbww** [comment]
Applied the patch, and added the shared-lib example.  Thank you both.
