### ISSUE TITLE
Comparing two instances of cctz::time_zone

### ISSUE THREAD

**Issue by Siesh1oo** [google/cctz#32]
What is the right way to compare two instances of cctz::time_zone? Should there be some public implementation of operator == in class cctz::time_zone?

Rationale: At runtime time zones are loaded based on their name, often provided by user or external input. As multiple places and names can be located in/point to the same time zone (e.g. "America/Kentucky/Louisville", "America/New York" and "EST5EDT"), it is desirable to be able to check whether the two instances are referring to the same time zone without naively comparing the timezone name.

**Comment by devbww** [comment]
What would be the definition of equality?  Identical transitions across time?  If so, then America/Kentucky/Louisville, America/New_York and EST5EDT are not equal.  And if not, then even talking about "equality" seems problematic.

In general we have the opinion that asking the equality question is a step in the wrong direction.  What would you do with the answer?  Perhaps you can expand on your "it is desirable to be able to check" use case.

Full disclosure: We do have time-zone equality in our (earlier) internal version, and across X million lines of code it is only used a handful of times, almost exclusively in unit tests and legacy wrappers.

**Comment by Siesh1oo** [comment]
I see, defining equality as identity of all transitions over all times in history would probably be of limited use (presumably returning mostly symlinks in tzdata).

I had the weaker assumption of "current" transition equality in mind when asking this question, but now I understand the problems of the fuzzy definition. The equality query would need at least an argument specifying the time interval, on which equality is checked? Probably too cumbersome for the purpose of unifying and streamlining input data.

Thank you for clarification.

**Comment by devbww** [comment]
> The equality query would need at least an argument specifying the time interval, on which equality is checked? Probably too cumbersome for the purpose of unifying and streamlining input data.

Right.  We have considered API points for navigating the transitions within a time zone, but decided that these were not operations to be encouraged in general.

**Comment by devbww** [comment]
For what it is worth, we did recently add "bool operator==(time_zone lhs, time_zone rhs)", which is defined as two time zones loaded using the same name and therefore having identical transitions over time.  It is mostly to allow merging our internal version though (mentioned above), so I still wouldn't recommend doing anything with it.  I hoping we might still eliminate it again.
