### ISSUE TITLE
Clang static analyzer report

### ISSUE THREAD

**Issue by Siesh1oo** [google/cctz#33]
Hi,

the clang static analyzer (scan-build) reports a minor issue in cctz.git/src/time_zone_info.cc: 

```
622	  // Copy all the abbreviations.
623	  abbreviations_.assign(bp, hdr.charcnt);
624	  bp += hdr.charcnt;
625	 
626	  // Skip the unused portions. We've already dispensed with leap-second
627	  // encoded zoneinfo. The ttisstd/ttisgmt indicators only apply when
628	  // interpreting a POSIX spec that does not include start/end rules, and
629	  // that isn't the case here (see "zic -p").
630	  bp += (8 + 4) * hdr.leapcnt;  // leap-time + TAI-UTC
631	  bp += 1 * hdr.ttisstdcnt;     // UTC/local indicators
632	  bp += 1 * hdr.ttisgmtcnt;     // standard/wall indicators
Value stored to 'bp' is never read
```

Indeed, this last modification of pointer bp seems to be dead code. Maybe some unintentional left-over from earlier reorganization?

**Comment by devbww** [comment]
I agree that those three lines, 630, 631, and 632 do not have any forward dependencies, but they are intentional, and I don't think they should be removed.  Just because we're not going to read past the end of a buffer does not mean we should not advance the pointer all the way to the end of the buffer.

We could add some kind of `assert(bp == tbuf.data() + tbuf.size())` check to try to silence your warning.

**Comment by Siesh1oo** [comment]
This sounds like a good solution, reveals intention and adds a sanity check against regression.

**Comment by devbww** [comment]
Unfortunately it probably doesn't work as assert() usually disappears under NDEBUG.

Can you verify that just "static_cast<void>(bp);" works for you?

**Comment by Siesh1oo** [comment]
The simple assert-based approach works fine. Clang's scan-build (and as far I know, all common other static analyzers too), use assertions to prune the analysis tree to reduce the space of possible code paths to manageable size. The scan-build command patches the compiler flags to explicitly enable assertions (cf. https://clang-analyzer.llvm.org/scan-build.html#recommended_debug and https://clang-analyzer.llvm.org/annotations.html#custom_assertions).

The following patch resolves the issue:

```
$ git diff
diff --git a/src/time_zone_info.cc b/src/time_zone_info.cc
index fe56bdc..28e2afa 100644
--- a/src/time_zone_info.cc
+++ b/src/time_zone_info.cc
@@ -33,6 +33,7 @@
 #include "time_zone_info.h"
 
 #include <algorithm>
+#include <cassert>
 #include <cerrno>
 #include <chrono>
 #include <cstdint>
@@ -462,6 +463,8 @@ bool TimeZoneInfo::Load(const std::string& name, FILE* fp) {
   bp += 1 * hdr.ttisstdcnt;     // UTC/local indicators
   bp += 1 * hdr.ttisgmtcnt;     // standard/wall indicators
 
+  assert(bp == tbuf.data() + tbuf.size());
+
   future_spec_.clear();
   if (tzh.tzh_version[0] != '\0') {
     // Snarf up the NL-enclosed future POSIX spec. Note
```

**Comment by devbww** [comment]
Applied.  Thanks.
