### ISSUE TITLE
console debug output on OSX 

### ISSUE THREAD

**Issue by Siesh1oo** [google/cctz#37]
Without having investigated this further, I'd like to report that on OS X 10.10.5 cctz emits some debug output to the console:

```
localtime: Missing POSIX spec
EST5EDT: Missing POSIX spec
```

(Time zone and conversion results seem correct, though)
On linux, this is not happening.

**Comment by devbww** [comment]
Thanks.  Should now be fixed.  We don't need to complain about a missing future rule.

That said, it seems like the OS X zoneinfo compiler must be mighty old.  If it is not producing future rules then DST shifts are probably going to be "wrong" after 2037 (if that is even a meaningful thing to say).
