### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Electroninja** [google/cctz#4]
Just wondering how I could contribute to your project, I have been programming for quite some time, but I am kinda new to github.

**Comment by devjgm** [comment]
Hi. Thanks for your interest. There are a couple work items that we're already working on ourselves, but at this time, we don't have a good list of other work for eager contributors like yourself. I'll see if I can put together a list of work ideas sometime soon.

In the meantime, feel free to install bazel, build the code, test the code, use the API and let us know if you find any bugs. Thanks!
