### ISSUE TITLE
documentation suggestion for Windows data files

### ISSUE THREAD

**Issue by michaeladamkatz** [google/cctz#43]
In this discussion of a Windows user trying to get cctz to work on Windows

https://groups.google.com/forum/#!topic/cctz/3tG-iyL3nf4

to get the binary zoneinfo files onto Windows she installs cygwin and runs zic.

It would be nice to put this information somewhere in the basic documentation, since Windows users need to bring in this zoneinfo data manually since Windows doesn't provide it in the needed format. (Some of the other steps from that thread would also be useful to include, such as #ifdef'ing out noexcept.)

However, the other important point to make about the zoneinfo files is that the incompatibility across platforms only seems to stem from big-endian/little-endian issues. So if you have a Mac (or other Linux) on an Intel machine (any modern Mac), I believe you can just .zip the zoneinfo directory and bring it over to your PC. I did this and everything seems to work fine. This was an easier process for me than having to install cygwin.

In fact it would be nice for you guys to include a .zip of the latest zoneinfo files right on this github site. Even for Mac/Linux people, packaged apps might want to include the data in app itself to have a backup plan it it's not available on the user's machine for some reason.

**Comment by devbww** [comment]
We'd be happy to add any concise instructions for Windows users to the README file, but someone who has actually figured out how to do it would need to draft them.  We were unaware of the "noexcept" issue, for example.

As for the zoneinfo files, there should be no endian-ness issues.  Multi-byte integers are encoded MSB first, and CCTZ decodes these as the file is read (as should all zoneinfo readers).  So, the same zoneinfo files should work on all systems.

If there is no convenient place to access pre-compiled zoneinfo data then I believe we could add them here.  Let me look into it.

Thanks.

**Comment by devbww** [comment]
We have added a copy of the pre-compiled zoneinfo data to testdata/zoneinfo.  testdata/README.zoneinfo describes how it was built.  The data is currently 2017c, and we'll keep to up to date as new releases are made.
