### ISSUE TITLE
undefined reference to 'clock_gettime'

### ISSUE THREAD

**Issue by tfarina** [google/cctz#47]
nal/benchmark/src/timers.pic.o:timers.cc:function benchmark::ProcessCPUUsage(): error: undefined reference to 'clock_gettime'
bazel-out/local-fastbuild/bin/external/benchmark/_objs/benchmark/external/benchmark/src/timers.pic.o:timers.cc:function benchmark::ThreadCPUUsage(): error: undefined reference to 'clock_gettime'
collect2: error: ld returned 1 exit status

I'm building on Ubuntu/Linux 12.04.

**Comment by devbww** [comment]
I believe the answer here is that prior to glibc 2.17 you need to link in the "real time" library.  So, you'll have to figure out how to get "-lrt" to the linker of the affected targets (probably just the benchmarks, which you could also just omit if you're not interested in running them).

**Comment by devjgm** [comment]
@tfarina how are you building? Are you using our bazel configs? Our Makefile? Your own make file? Or something else? Also, is this still an issue or has it been resolved?

**Comment by devbww** [comment]
Assuming the issue has been resolved, so closing.
