### ISSUE TITLE
Timezone rules change over the time. Have you thought about that?

### ISSUE THREAD

**Issue by sompylasar** [google/cctz#49]
`cctz::load_time_zone` takes only the timezone name as a parameter, and returns the timezone rules that are in effect at the current moment in time. But the timezone rules themselves change over time.

> Time zones often have a history of disparate rules that apply only for certain periods, because the rules may change at the whim of a region's local government.

What if the user needed a calendar representation of an absolute timestamp at the time of that timestamp, i.e. what was the civil time (the "wall time") at that time?

References:
* http://codeofmatt.com/2016/04/23/on-the-timing-of-time-zone-changes/
* https://blogs.msdn.microsoft.com/ie/2013/03/25/spring-forward-advancing-historical-date-and-time-calculations-on-the-web/

Thank you.

**Comment by timparenti** [comment]
Historical timekeeping rules for any given location are already handled by the various time zone definitions in the [IANA time zone database](https://www.iana.org/time-zones) (also known as `tz`), which is used by this project.

For example, when [this project](https://github.com/google/cctz/blob/2e86a776379ec6f2a60f4a6595a3b68cd3961cb4/examples/example1.cc#L23) uses code like:
```c++
load_time_zone("America/Los_Angeles", &lax);
```
it refers to the `America/Los_Angeles` zone as defined by `tz`.  In [`tz`'s underlying data format](https://github.com/eggert/tz/blob/ba0cc9cc465a99eb03a7b3ef05a25ca8b2e716c6/northamerica#L480), that is represented (in part) as follows:

```
# Rule	NAME	FROM	TO	TYPE	IN	ON	AT	SAVE	LETTER
Rule	CA	1948	only	-	Mar	14	2:01	1:00	D
Rule	CA	1949	only	-	Jan	 1	2:00	0	S
Rule	CA	1950	1966	-	Apr	lastSun	1:00	1:00	D
Rule	CA	1950	1961	-	Sep	lastSun	2:00	0	S
Rule	CA	1962	1966	-	Oct	lastSun	2:00	0	S
# Zone	NAME		GMTOFF	RULES	FORMAT	[UNTIL]
Zone America/Los_Angeles -7:52:58 -	LMT	1883 Nov 18 12:07:02
			-8:00	US	P%sT	1946
			-8:00	CA	P%sT	1967
			-8:00	US	P%sT
```

As you can see, this encodes much historical information about how local civil time has been computed for this location, including UTC offsets and daylight saving time observances according to multiple rule sets.  `tz` compiles such data for all its zones, and distributes a how-to guide on reading and interpreting it, which you can read at [ftp://ftp.iana.org/tz/tz-how-to.html](ftp://ftp.iana.org/tz/tz-how-to.html).

This project simply makes use of `tz` data.

**Comment by devbww** [comment]
As Tim mentioned, this is already how cctz and the tzdata works.  An "absolute-time + time-zone -> civil-time" conversion uses the UTC offset that was current at that absolute time, not what offset was in force at load_time_zone() time.
