### ISSUE TITLE
New release for Abseil compatability?

### ISSUE THREAD

**Issue by njlr** [google/cctz#52]
I am trying to package [Abseil](https://github.com/abseil/abseil-cpp), which depends on `cctz`. However, it seems that Abseil requires features of cctz that are not in the `v2.0.0` release. 

For example: 

```
absl/time/time.h:1041:41: error: no member named 'name' in 'cctz::time_zone'
  std::string name() const { return cz_.name(); }
```

Are there plans to make another release that contains the features required by Abseil?

**Comment by devjgm** [comment]
Well, according to Abseil's mantra, you should "live at head" ;-)

But I made a 2.1 release w/ a snapshot of cctz as of Abseil's initial release. Going forward cctz releases will likely not correspond with Abseil updates. Prefer to live at head, like Abseil does.
