### ISSUE TITLE
TimeZones.LoadZonesConcurrently test fails on mips platform

### ISSUE THREAD

**Issue by gladk** [google/cctz#63]
Dear all,

cctz was recently added to Debian archive [1] and was successfully built almost on all release relevant platforms [1].

There is only a problem with the TimeZones.LoadZonesConcurrently test, which is failing with " terminate called without an active exception" error:

`Start 2: time_zone_lookup_test                                                                                                                                                      [95/1830]
                                                 
2: Environment variables:                                     
2:  TZDIR=/usr/share/zoneinfo                                       
2: Test timeout computed to be: 1500         
2: Running main() from gtest_main.cc             
2: [==========] Running 31 tests from 7 test cases.
2: [----------] Global test environment set-up.                                               
2: [----------] 1 test from TimeZones              
2: [ RUN      ] TimeZones.LoadZonesConcurrently
2: terminate called without an active exception
2/4 Test #2: time_zone_lookup_test ............***Exception: Other  0.04 sec
test 3                                                                    
    Start 3: time_zone_format_test`

For now we disable this test for mips, but it would be good to fix it properly.

[1] https://buildd.debian.org/status/package.php?p=cctz

Thanks you

**Comment by devbww** [comment]
> cctz was recently added to Debian archive

:-)

> and was successfully built almost on all release relevant platforms

:-(

Unfortunately, the test log doesn't tell us too much.

```
[ RUN      ] TimeZones.LoadZonesConcurrently
terminate called without an active exception
```
Is there some way we can see a stacktrace showing where terminate() was called?  It looks like the failures are only on 32-bit mips.  Are there known issues with <thread> on those platforms?  Can we get access to a machine to give us a better idea of what is going on?

Thanks.

**Comment by devbww** [comment]
s/known issues with on those platforms/known issues with &lt;thread&gt; on those platforms/

[Markdown swallowed my angled brackets.]

**Comment by gladk** [comment]
Hi Bradley,

thanks for your answers. I have attached the gdb output. Maybe it can help more to analyze the issue.

I will try to ask mips-porters about known issues with threads on 32-bit platforms. Unfortunately it is almost impossible to access porter-machines for non-Debian developers. But if you need to test there
some specific code, I can try to do it and let you know.

[gdb.txt.tar.gz](https://github.com/google/cctz/files/1483977/gdb.txt.tar.gz)

**Comment by gladk** [comment]
It looks like there are some kind of overflow on those weak platforms. From gdb output:

`failures = std::set with 2012631200 elements<error reading variable: Cannot access memory at address 0xc>` 

Reducing the number of threads from 256 to 250 here [1] resolves the problem [1]. Would you accept this change if I prepare merge request? Has this number 256 there any special meaning.

https://github.com/google/cctz/blob/master/src/time_zone_lookup_test.cc#L681

Thanks

**Comment by devbww** [comment]
> Reducing the number of threads from 256 to 250 resolves the problem.

Thanks Anton.

> Has this number 256 there any special meaning.

No, it was mostly chosen at random.  I've committed a change to reduce the thread count from 256 to 128.  There is no need for us to be close to any limit as long as we're getting over the number of cores.

Please close this issue when you're sure it is all working for you.

Thanks again.

**Comment by gladk** [comment]
I can confirm that it builds fine on all platforms now with 250 threads [1]. So I am sure that for 128 it will
work as well.

[1] https://buildd.debian.org/status/package.php?p=cctz

Thanks
