### ISSUE TITLE
parse and ParseInt doesn't consider number length when parsing. 

### ISSUE THREAD

**Issue by gcamp** [google/cctz#65]
I have this string that was parsing correctly when using c date APIs. 

> Failed to parse '20180116 13:00' with format '%Y%m%d %H:%M'

Looking quickly at the code, the part of ParseInt is not bounded by the max length of a number (ie 4 for years). 

However, I get why this is a complex question. How do you know if years is really in the 4 numbers? Can't parse years before 1000?

I'm thinking of doing a patch for this, but would like maybe some guidance as what you think is the best approach.

**Comment by devjgm** [comment]
See https://github.com/google/cctz/blob/master/include/cctz/time_zone.h#L255

You'll want to parse using `%E4Y` if you want exactly 4 year digits.

**Comment by gcamp** [comment]
I just saw the %E4Y extension, which is probably the answer I was looking for.
