### ISSUE TITLE
Will the precompiled tz data files be updated if new ones are available?

### ISSUE THREAD

**Issue by mireiner** [google/cctz#67]
Hi there,

in your forum https://groups.google.com/forum/#!forum/cctz Bradley White wrote on 26. October 2017:
"Update: We have now included pre-compiled zoneinfo files in the CCTZ distribution, so Windows users should just be able to copy those."

Well done, thank you very much! This is a big help for all Windows users.

New timezone data files are updated once or twice a year these days. The last update 'tzdata2018b' happened on 17. January 2018 at https://www.iana.org/time-zones.

If new time zone data files are available, will cctz update their precompiled timezone data files also (located in its archive file 'cctz-master.zip' under \testdata\zoneinfo)?

How to check which version of the precompiled time zone data files are included in the cctz archive file? Is there a readme file for this or any other way to check it?

If there is no way to check the version of the included precompiled tz data files yet, it would be great if this feature could be added to cctz.

Best regards,
mireiner

**Comment by timparenti** [comment]
Just a note that issues were found with `tz` versions 2018a and 2018b after release but before announcement.  **2018c,** which addresses these issues, [is expected in the coming days](http://mm.icann.org/pipermail/tz/2018-January/025872.html), so apart from the longer-term considerations here, that is likely a contributing factor to why there haven't (yet) been updates in this particular case.

**Comment by devbww** [comment]
> If new time zone data files are available, will cctz update their precompiled timezone data files also (located in its archive file 'cctz-master.zip' under \testdata\zoneinfo)?

Yes.

As was just noted, no 2018* tz release has yet been made (despite updates with such names being visible).

> How to check which version of the precompiled time zone data files are included in the cctz archive file? Is there a readme file for this or any other way to check it?

No, the data files are not self describing, and the only thing including the version in our repository is the commit message that made the updates.

> If there is no way to check the version of the included precompiled tz data files yet, it would be great if this feature could be added to cctz.

I'll look into including the version somewhere easier to see.

**Comment by mireiner** [comment]
Hi timparenti,
thank you for the info.

Hi devbww,
<blockquote>
<p>I'll look into including the version somewhere easier to see.</p>
</blockquote>

Thank you, that would be really helpfull! 
One solution might be to include the tz data version info in file 'README.zoneinfo' located in the folder cctz-master\testdata. If one wants to use the zoninfo files Its hard to overlook that file.

**Comment by devbww** [comment]
The testdata/zoneinfo/... files have been updated to 2018c.

A new file, testdata/version, has been added to capture the version of those zoneinfo files.
