### ISSUE TITLE
Date-only & Time-only operations

### ISSUE THREAD

**Issue by mj1856** [google/cctz#8]
This is more of a question than an issue.

This library feels to me like the C++ answer to [Java 8's `java.time`](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) package, or to [Noda Time](http://nodatime.org/) in .NET.

In those libraries (and many others), there are other APIs within the civil time domain that handle date-only or time-only operations.  Are these things you're considering for cctz?  Or is it just focused on the time-point to breakdown conversion problem?

For example, `cctz:Breakdown` is conceptually identical to `LocalDateTime` in the aforementioned libraries.  However, those also have `LocalDate` and `LocalTime` structures, and cctz doesn't, as far as I can tell.

Use cases for these include:
- Representing a whole civil day, rather than just a time within the day, such as birth dates.
- Representing a time-of-day that isn't bound to a specific date, such as a repeating time.

**Comment by devbww** [comment]
Hi Matt,

We do have another "civil time" library (not open sourced yet) that deals with time-zone independent date/times.  It models Y, YM, YMD, YMDh, YMDhm, and YMDhms values, with appropriate operations on each, and conversions between them.  We are working on unifying it with the cctz release.

Bradley

**Comment by devjgm** [comment]
Matt,

We just release CCTZ v2., which does include a full civil-time library for date-only calculations. See the README.md at https://github.com/google/cctz for more info.

**Comment by mj1856** [comment]
Thanks, I'll take a look! :)
