### ISSUE TITLE
Missing CMake install rules

### ISSUE THREAD

**Issue by Mizux** [google/cctz#82]
Currently cctz doesn't provide CMake install rule which is a pain for CMake users to integrate it.

On the same subject:

* There was a proposal in the PR #54, but you ask for removal cf https://github.com/google/cctz/pull/54/commits/79c7c0ad5e488e405e3c70aca519311bad8804d6
* Distro maitainers have to maintain patchs to do it https://salsa.debian.org/science-team/cctz/blob/d335bb4309d960b88e5f9024983f6f934a6db366/debian/patches/0001-Compile-shared-lib-and-install-it.patch
* Same for vcpkg, microsoft dev already provide an install rule whithout waiting for you... https://github.com/Microsoft/vcpkg/blob/ab48a71c9af25041ab29a0d8e62a3cdf380638a5/ports/cctz/CMakeLists.txt#L21-L36
* On the other hands Makefile **already** provide install rules cf https://github.com/google/cctz/blob/a2acba2966660a9bfe9ab66efcfad573d91f56b6/Makefile#L85-L97
* For https://github.com/google/or-tools we are currently migrating from "custom" base to abseil -> I have to patch cctz and maintain it cf https://github.com/google/or-tools/blob/abseil/patches/cctz-master.patch
EDIT: Abseil-cpp now has a cctz version embedded...

**Comment by urykhy** [comment]
any chance to have a release with this feature ?

**Comment by devjgm** [comment]
@urykhy That's probably possible. But two questions:

1. Do you use cctz directly in your code?
2. Do you use Abseil? [Abseil](https://github.com/abseil/abseil-cpp) has other/related time libraries (based on cctz), so I'm curious if you saw those.
3. Have/can you confirm that the make install rule in this repo at head works for you? I'd like to avoid making a release that still doesn't work :-)

**Comment by urykhy** [comment]
1. yes, i use cctz directly.
2. no.
3. i confirm master branch ok for me (i want `make install` and cmake import target, there features works as expected)

**Comment by devbww** [comment]
@urykhy ... I just released "CCTZ version 2.3".  Let us know if that doesn't work for you.  Thanks.

**Comment by urykhy** [comment]
@devjgm It works like a charm, Thanx!

**Comment by devjgm** [comment]
@urykhy You're welcome, but it was @devbww who did the release for you :-)
