### ISSUE TITLE
Conan Package Support

### ISSUE THREAD

**Issue by uilianries** [google/cctz#85]
Hello,

Do you know about [Conan](https://github.com/conan-io)?

Conan is modern dependency and package manager for C/C++. And will be great if your library will be available via package manager for other developers.

Now we have famous C++ projects, including Google Flatbuffers. We could support you writing a recipe and publishing your packages on Bintray.

If you have any questions, just ask :-)

**Comment by nine** [comment]
There is already a conan package available: https://conan.io/center/recipes/cctz

@uilianries so can you close this ticket?

**Comment by uilianries** [comment]
Thank you for pinging! Closing it now.
