### ISSUE TITLE
Recent commit 805a025 may break non-English mac users

### ISSUE THREAD

**Issue by wada314** [google/cctz#98]
Hello, while I'm debugging my strange segmentation fault, I reached to the patch 805a025.
https://github.com/google/cctz/commit/805a025a896994ed507c9704cce15221bac6a632#diff-369c46982c3f44e7ed265e8576edfd4d

This patch introduced a call to `CFStringGetSystemEncoding()` mac api, but this api seems to be broken in our non-English mac machines (I confirmed in Japanese language). This function returns 0 (`kCFStringEncodingMacRoman`) for English users, but it returns 1 for Japanese users, which is an undefined value!
https://opensource.apple.com/source/CF/CF-299/String.subproj/CFString.h.auto.html

My mac version: 10.14.3
My xcode version: Version 10.0 (10A255)

**Comment by devjgm** [comment]
It looks to me like a returned value of 1 means `kCFStringEncodingMacJapanese = 1`

https://developer.apple.com/documentation/corefoundation/cfstringencodings/kcfstringencodingmacjapanese?language=objc

Do you have a small test case that shows this problem, that maybe I can use to reproduce this on my own machine?

**Comment by devjgm** [comment]
@wada314 Can you please take a look at https://github.com/google/cctz/pull/99, and if possible, patch it in to see if that fixes your problem? If so, I'll mere that change. I'll wait to hear back from you before merging.
